### ISSUE TITLE
Outline on Links in Firefox

### ISSUE THREAD

**Issue by ximex** [ashleydw/lightbox#121]
https://css-tricks.com/removing-the-dotted-outline/

```css
.ekko-lightbox-nav-overlay a {
  z-index: 100;
  display: block;
  width: 49%;
  height: 100%;
  font-size: 30px;
  color: #fff;
  text-shadow: 2px 2px 4px #000;
  opacity: 0;
  outline: none; /* <<<<< Insert this */
  filter: dropshadow(color=#000000, offx=2, offy=2);
  -webkit-transition: opacity 0.5s;
     -moz-transition: opacity 0.5s;
       -o-transition: opacity 0.5s;
          transition: opacity 0.5s;
}
```
